### PR TITLE
Develop/mamas cookin

### PR DESCRIPTION
**Pull request by devironJ**

### CODE REVIEW

**Comment by scottnakada** [comment]
Devon,

            Attached is a powerpoint slideset for my passion project, to explain what I’d like to do.  I’m volunteering at a TJ orphanage this afternoon; but will put together the AppGyver slideset tonight.  I couldn’t figure out how to get to the slack room with the post-it notes board.

            We should probably put together a sample project, that is entered loaded into GitHub, and is posted live (through Heroku), and has links to mobile apps through AppGyver, to show people tomorrow, as well as a sample portfolio web-page, which links everything together.

 

                                                                                                                        Scott

**Comment by scottnakada** [comment]
Oops,

               Here is the updated slideset.

                              Scott

 

From: scottnakada@gmail.com [mailto:scottnakada@gmail.com] 
Sent: Sunday, March 8, 2015 10:50 AM
To: 'devironJ/mommascookingapp'
Subject: SlideSet for Passion Project

 

Devon,

            Attached is a powerpoint slideset for my passion project, to explain what I’d like to do.  I’m volunteering at a TJ orphanage this afternoon; but will put together the AppGyver slideset tonight.  I couldn’t figure out how to get to the slack room with the post-it notes board.

            We should probably put together a sample project, that is entered loaded into GitHub, and is posted live (through Heroku), and has links to mobile apps through AppGyver, to show people tomorrow, as well as a sample portfolio web-page, which links everything together.

 

                                                                                                                        Scott

**Comment by devonJS** [comment]
I still dont see it haha, but here is my slide show for Monday on Yeoman

https://docs.google.com/presentation/d/10Dz7oGnRTi79xLVDxxM4ylW0GUQKJq9GDdkwVgSkr2Y/edit?usp=sharing

I invited you to the slack chat again, check your email

**Comment by scottnakada** [comment]
Devon,

               The slide deck seems really good; but I’m concerned that it may be too long.  There are some people in the class who won’t understand the material in the slides, and there are others who will get bored talking about some of the material.  It might be more effective to tell them only what they need to know; but I’ll let you decide.  Some suggestions are:

 

1)      You might want to mention the installation command for yeoman: npm install –g yo, and mention that it only needs to be run once

2)      Slide 2 of your deck isn’t necessary (doing the global install of generator-angular-fullstack, puts the latest from the git onto your system

3)      You might want to mention that the global install of the generator-angular-fullstack only needs to be done once globally

4)      Slide 5, you might want to mention that we are creating a new project with WebStorm

5)      Slides 11-12, might want to save discussion of ng-view will we get to multi-page

6)      14-28, not sure we need to cover thing stuff, most people won’t include it in their own pages

7)      Slides 29-33, people like Merek and Fox, will probably be insulted that you are teaching them 2-way data binding, and the people who don’t know 2-way data binding by now, probably will be overwhelmed with everything else we are covering

8)      Might want to cover how to publish the web-site to GitHub

9)      Might want to cover how to publish the web-site to Heroku, so it will be live on the web

 

Anyway, just some thoughts about the slides.  I’ve attached a PDF of my Passion Proj slides.  Hopefully you can read them in pdf format.  I’m starting to work on the AppGyver slides now.

 

                                                                           Scott

**Comment by scottnakada** [comment]
Devon,

               I’m running a little late; but here are my slides.

                                                            Scott

**Pull request merged**
